# Generated by Django 5.1.2 on 2024-10-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
