# Generated by Django 5.1.2 on 2024-10-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
