# Generated by Django 5.1.2 on 2024-10-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Project',
            new_name='project',
        ),
    ]
