# Generated by Django 5.1.2 on 2024-11-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='description',
            new_name='descripcion',
        ),
    ]
