# Generated by Django 5.1.2 on 2024-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_rename_description_productos_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="productos",
            name="imagen_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
