# Generated by Django 5.1.2 on 2024-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
