# Generated by Django 5.1.2 on 2024-12-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_eventos_imagen_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='imagen_url',
            new_name='google_maps',
        ),
    ]
