# Generated by Django 5.1.2 on 2024-12-05 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_eventos_google_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='horario',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
