# Generated by Django 5.1.2 on 2024-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_eventos_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='sellado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='single',
            field=models.BooleanField(default=False),
        ),
    ]
