# Generated by Django 5.1.2 on 2024-12-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_productos_sellado_productos_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='google_maps',
            field=models.CharField(max_length=500),
        ),
    ]
