# Generated by Django 5.1.2 on 2024-12-06 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_alter_eventos_google_maps"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoCarta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="productos",
            name="estado_carta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.estadocarta",
            ),
        ),
    ]
